# One-off data-prep script (not run as part of the Shiny app itself).
#
# Generates data/modelled/waterbodyInfo.txt: one short-metadata block per EA
# water body that has modelled chemical concentration data, in the same
# "### <id>" block format as data/measured/sitesInfo.txt, so both are read by
# the same parse_entity_info() parser in app.R. Unlike sitesInfo.txt (19
# hand-written blocks), there are 336 water bodies here - far too many to
# author narrative summaries for by hand - so this file is machine-generated
# from the real name/operational-catchment attributes already available, with
# an explicit placeholder summary and no fabricated population/land-cover
# figures.
#
# Re-run whenever gis-data/EA_Waterbodies_AOI.geojson,
# data/waterbody_operational_catchment.csv, or the set of water bodies
# present in the modelled parquet changes. Do not hand-edit the output file.
#
# Output (consumed by app.R):
#   data/modelled/waterbodyInfo.txt

library(sf)
library(dplyr)
library(arrow)
library(here)

waterbodies <- read_sf(here("gis-data", "EA_Waterbodies_AOI.geojson")) %>%
  st_drop_geometry() %>%
  select(water_body, water_bod0)

opcat <- read.csv(here("data", "waterbody_operational_catchment.csv"))

wb_chem_dataset <- open_dataset(here(
  "data-chem", "2_Modelling_results_by_waterbody_monthly_conc_ng_per_L",
  "2_Modelling_results_by_waterbody_monthly_conc_ng_per_L.parquet"
))
modelled_ids <- wb_chem_dataset %>%
  distinct(waterbody_id) %>%
  collect() %>%
  pull(waterbody_id) %>%
  sort()

info <- waterbodies %>%
  filter(water_body %in% modelled_ids) %>%
  left_join(opcat, by = "water_body") %>%
  arrange(water_body)

stopifnot(nrow(info) == length(modelled_ids))

header <- c(
  "# waterbodyInfo.txt",
  "#",
  "# [DUMMY PLACEHOLDER DATA] -- This file does not yet contain real water body",
  "# background information. Summaries below are illustrative placeholders; unlike",
  "# sitesInfo.txt, no population or land cover figures are included at all, since",
  "# no verified per-water-body catchment data exists yet to base them on.",
  "#",
  "# Format: one block per modelled water body, starting with \"### <water_body>\"",
  "# where <water_body> matches the waterbody_id column in the modelled chemical",
  "# concentration parquet and the water_body property in EA_Waterbodies_AOI.geojson.",
  "# Each block has \"Key: Value\" lines.",
  "#",
  "# This file is machine-generated by scripts/build_waterbody_info.R - re-run that",
  "# script to regenerate it rather than hand-editing entries here.",
  ""
)

block_lines <- lapply(seq_len(nrow(info)), function(i) {
  opcat_name <- info$opcat_name[i]
  c(
    paste0("### ", info$water_body[i]),
    paste0("Water body: ", info$water_bod0[i]),
    paste0(
      "Summary: [DUMMY PLACEHOLDER] No verified background information is available ",
      "yet for this water body."
    ),
    paste0("Operational catchment: ", ifelse(is.na(opcat_name), "None", opcat_name)),
    ""
  )
})

out_path <- here("data", "modelled", "waterbodyInfo.txt")
dir.create(dirname(out_path), recursive = TRUE, showWarnings = FALSE)
writeLines(c(header, unlist(block_lines)), out_path)

cat(sprintf(
  "Wrote data/modelled/waterbodyInfo.txt (%d water body blocks)\n",
  nrow(info)
))
